name: Format
on:
  pull_request:

jobs:
  cpp:
    name: C/C++
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ${{ github.event.repository.name }}
        uses: actions/checkout@v3
      - name: Run clang-format
        uses: jidicula/clang-format-action@v4.9.0
        with:
          clang-format-version: "15"
